
services:
# 서비스 서버 개별 관리

# 공통 DB 관리
  postgres:
    image: 'postgres:16.4'
    environment:
      - 'POSTGRES_DB=logistics'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=logistics'
    ports:
      - '54322:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:

