server:
  port: 19095

spring:
  application:
    name: hub-service
  datasource:
    url: jdbc:postgresql://localhost:15432/hubdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver # 써야됨?
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:19090/eureka/

# redis 캐시 설정도 필요함